Adverts/Components/AdvertCardsViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Adverts.Components
{
    public class AdvertCardsViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync()
        {
            return View();
        }
    }
}

Adverts/Controllers/AdvertController.cs
using Adverts.Core.Models.Domains;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Dynamic;
using Adverts.Persistence.Repositories;
using Adverts.Persistence;
using Adverts.Core.ViewModels;
using Adverts.Persistence.Extensions;
using Microsoft.AspNetCore.Hosting;
using System.IO;
using Microsoft.AspNetCore.Http;
using System.Collections.ObjectModel;
using Adverts.Core;

namespace Adverts.Controllers
{
    [Authorize]
    public class AdvertController : Controller
    {
        private IUnitOfWork _unitOfWork;
        private IImage _image;
        public AdvertController(IUnitOfWork unitOfWork, IImage image)
        {
            _unitOfWork = unitOfWork;
            _image = image;
        }

        [AllowAnonymous]
        public async Task<IActionResult> GetAllAdverts()
        {
            var userId = User.GetUserId();
            var adverts = await _unitOfWork.Advert.GetAdverts();

            var vm = new AdvertsViewModel
            {
                Adverts = adverts,
                UserId = userId,
                Categories = await _unitOfWork.Category.GetCategories(),
                Conditions = await _unitOfWork.Condition.GetConditions()
            };

            return View(vm);
        }

        [AllowAnonymous]
        [HttpPost]
        public async Task<IActionResult> GetAllAdverts(AdvertsViewModel vm)
        {
            var userId = User.GetUserId();

            if (!vm.IsMyAdverts)
                userId = null;

            var adverts = await _unitOfWork.Advert.GetAdverts(vm.Title, vm.CategoryId, vm.ProductId, vm.ConditionId, userId);

            vm = new AdvertsViewModel
            {
                Adverts = adverts,
                UserId = User.GetUserId()
            };

            return PartialView("_AdvertCards", vm);
        }

        public IActionResult AddAdvert(int advertId = 0, bool isSuccess = false)
        {
            ViewBag.IsProductsListDisabled = true;
            var userId = User.GetUserId();
            var advert = new Advert { UserId = userId };

            ViewBag.IsSuccess = isSuccess;
            ViewBag.AdvertId = advertId;

            var vm = new AdvertViewModel
            {
                Advert = advert
            };
            return View(vm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddAdvert(AdvertViewModel vm)
        {
            if (vm.CategoryId == null)
                ViewBag.IsProductsListDisabled = true;

            var userId = User.GetUserId();
            vm.Advert.UserId = userId;

            if (ModelState.IsValid)
            {
                await _image.UploadImages(vm);

                int advertId = await _unitOfWork.Advert.AddAdvert(vm.Advert);
                return RedirectToAction("AddAdvert", new { advertId = advertId, isSuccess = true });
            }

            return View(vm);
        }

        [AllowAnonymous]
        public async Task<IActionResult> GetAdvert(int advertId)
        {
            var advert = await _unitOfWork.Advert.GetAdvert(advertId);

            return View(advert);
        }

        [HttpPost]
        public async Task<IActionResult> RemoveAdvert(int advertId)
        {
            try
            {
                var userId = User.GetUserId();
                await _unitOfWork.Advert.RemoveAdvert(advertId, userId);
                await _unitOfWork.Complete();
            }
            catch (Exception ex)
            {
                return Json(new { success = false, message = ex.Message });
            }
            return Json(new { success = true });
        }

        [AllowAnonymous]
        [HttpGet]
        public async Task<ActionResult> GetProducts(int categoryId)
        {
            IEnumerable<Product> products = await _unitOfWork.Product.GetProductsByCategory(categoryId);
            var json = Json(products);
            return Json(products);
        }

    }
}

Adverts/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Adverts.Models.ViewModels;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Adverts.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Adverts/Views/Advert/AddAdvert.cshtml
@model Adverts.Core.ViewModels.AdvertViewModel
@inject Adverts.Core.IUnitOfWork _unitOfWork

@{
    ViewData["Title"] = "Dodaj nowe ogłoszenie";
}

<div class="container">
    <h1 class="display-5 mb-3">Dodaj nowe ogłoszenie</h1>

    @if (ViewBag.IsSuccess == true)
    {
        <div class="alert alert-success alert-dismissible fade show" role="alert">
            <strong>Gratulacje!</strong> Udało Ci się dodać nowe ogłoszenie. <br />
            Kliknij <a asp-action="GetAdvert" asp-controller="Advert" asp-route-advertId="@ViewBag.AdvertId">tu</a> aby wyświetlić szczegóły.
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    }

    <form method="post" enctype="multipart/form-data" asp-action="AddAdvert" asp-controller="Advert" asp-antiforgery="true">
        <input asp-for="Advert.UserId" hidden />

        <div class="mb-2">
            <label asp-for="Advert.Title" class="form-label"></label>
            <input asp-for="Advert.Title" class="form-control" />
            <span asp-validation-for="Advert.Title" class="text-danger"></span>
        </div>

        <div class="mb-2">
            <label asp-for="CategoryId" class="form-label"></label>
            <select asp-for="CategoryId" class="form-control" asp-items='new SelectList(await _unitOfWork.Category.GetCategories(), "Id", "Name")' id="category">
                <option value="">-- wybierz kategorię --</option>
            </select>
            <span asp-validation-for="CategoryId" class="text-danger"></span>
        </div>

        <div class="mb-2">
            <label asp-for="Advert.ProductId" class="form-label"></label>
            <select asp-for="Advert.ProductId" class="form-control" asp-items='new SelectList(await _unitOfWork.Product.GetProductsByCategory(Model.CategoryId==null ? 0 : (int)Model.CategoryId), "Id", "Name")' id="product" disabled="@ViewBag.IsProductsListDisabled">
                <option value="">-- wybierz rodzaj produktu --</option>
            </select>
            <span asp-validation-for="Advert.ProductId" class="text-danger"></span>
        </div>

        <div class="mb-2">
            <label asp-for="Advert.Description" class="form-label"></label>
            <textarea asp-for="Advert.Description" class="form-control"></textarea>
            <span asp-validation-for="Advert.Description" class="text-danger"></span>
        </div>

        <div class="mb-2">
            <label asp-for="Advert.ConditionId" class="form-label"></label>
            <select asp-for="Advert.ConditionId" class="form-control" asp-items='new SelectList(await _unitOfWork.Condition.GetConditions(), "Id", "Name")'>
                <option value="">-- wybierz stan --</option>
            </select>
            <span asp-validation-for="Advert.ConditionId" class="text-danger"></span>
        </div>

        <div class="mb-2">
            <label asp-for="MainImageFile" for="customFile" class="form-label"></label>
            <input asp-for="MainImageFile" accept="image/jpeg, image/gif, image/png" class="form-control" id="customFile">
            <span asp-validation-for="MainImageFile" class="text-danger"></span>
        </div>

        <div class="mb-2">
            <label asp-for="FileGalleries" for="formFileMultiple" class="form-label"></label>
            <input asp-for="FileGalleries" accept="image/jpeg, image/gif, image/png" class="form-control" id="formFileMultiple" multiple>
            <span asp-validation-for="FileGalleries" class="text-danger"></span>
        </div>

        <div class="mb-2">
            <label asp-for="Advert.DateValid" class="form-label"></label>
            <input asp-for="Advert.DateValid" class="form-control" />
            <span asp-validation-for="Advert.DateValid" class="text-danger"></span>
        </div>

        <div class="mt-4">
            <input type="submit" value="Dodaj ogłoszenie" class="btn btn-primary" />
        </div>
    </form>
</div>

Adverts/Views/Advert/GetAdvert.cshtml
@model Adverts.Core.Models.Domains.Advert

@{
    ViewData["Title"] = "Szczegóły ogłoszenia";
}


<div class="container">
    <h1 class="display-5 mb-3">Szczegóły ogłoszenia</h1>
    <div class="row">
        <div class="col-md-6">
            <div id="carouselExampleCaptions" class="carousel slide" data-bs-ride="carousel">
                <div class="carousel-indicators">
                    @for (int i = 0; i < Model.AdvertGalleries.Count; i++)
                    {
                        <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="@i" class="@(i==0 ? "active" : "")" aria-current="@(i==0 ? "true" : "")" aria-label="Slide @(i+1)"></button>
                    }
                </div>
                <div class="carousel-inner">
                    @for (int i = 0; i < Model.AdvertGalleries.Count; i++)
                    {
                        <div class="@(i==0 ? "carousel-item active" : "carousel-item")">
                            <img src="@Model.AdvertGalleries.AsEnumerable().ElementAt(i).Url" class="d-block w-100" alt="@Model.AdvertGalleries.AsEnumerable().ElementAt(i).Name">
                        </div>
                    }

                </div>
                <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="visible"></span>
                </button>
                <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="visible"></span>
                </button>
            </div>
        </div>
        <div class="col-md-6">
            <div class="row">
                <div class="col-md-12">
                    <h1>@Model.Title</h1>
                </div>
            </div>
            <div class="list-group">
                <div class="list-group-item list-group-item-action">
                    <span class="fw-bold">Kategoria -</span> @Model.Product.Category.Name
                </div>
                <div class="list-group-item list-group-item-action"><span class="fw-bold">Produkt - </span> @Model.Product.Name</div>
                <div class="list-group-item list-group-item-action"><span class="fw-bold">Stan - </span> @Model.Condition.Name</div>
                <div class="list-group-item list-group-item-action"><span class="fw-bold">Data wygaśnięcia - </span> @(Model.DateValid==null ? "Brak" : Model.DateValid?.ToString("dd-MM-yyyy"))</div>
                <div class="list-group-item list-group-item-action">
                    <div class="d-flex w-100 justify-content-between">
                        <span class="mb-1 fw-bold">Opis</span>
                    </div>
                    <p class="mb-1">@Model.Description</p>
                </div>
            </div>
        </div>
    </div>
</div>

Adverts/Views/Advert/GetAllAdverts.cshtml
@model Adverts.Core.ViewModels.AdvertsViewModel
@inject Adverts.Core.IUnitOfWork _unitOfWork

@{
    ViewData["Title"] = "Ogłoszenia";
}

<div class="container">
    <h1 class="display-5 mb-3">Ogłoszenia</h1>

    <form id="filterForm" class="row row-cols-lg-auto g-3 align-items-center mb-3">
        <div class="col-12">
            <input asp-for="Title" class="form-control" placeholder="Tytuł" />
        </div>

        <div class="col-12">
            <select asp-for="CategoryId" asp-items="@(new SelectList(await _unitOfWork.Category.GetCategories(), "Id", "Name"))" class="form-control" id="category">
                <option value="">-- wybierz kategorię --</option>
            </select>
        </div>

        <div class="col-12">
            <select asp-for="ProductId" class="form-control" id="product" disabled>
                <option value="">-- wybierz rodzaj produktu --</option>
            </select>
        </div>

        <div class="col-12">
            <select asp-for="ConditionId" asp-items="@(new SelectList(await _unitOfWork.Condition.GetConditions(), "Id", "Name"))" class="form-control">
                <option value="">-- wybierz stan --</option>
            </select>
        </div>

        @if (User.Identity.IsAuthenticated)
        {
            <div class="col-12">
                <div class="form-check">
                    <input asp-for="IsMyAdverts" class="form-check-label" />
                    <label asp-for="IsMyAdverts"></label>
                </div>
            </div>
        }

        <div class="col-12">
            <button type="submit" class="btn btn-primary">Szukaj</button>
        </div>
    </form>

</div>

<div id="advertCards" class="row row-cols-1 row-cols-md-3 g-4">
    <partial name="_AdvertCards" model="Model" />
</div>


@section Scripts
{
    <script type="text/javascript">
        $(document).ready(function () {
            $('#filterForm').submit(function () {
                $.ajax({
                    type: "POST",
                    url: "@Url.Action("GetAllAdverts", "Advert")",
                    data: $(this).serialize(),
                    success: function (data) {
                        $('#advertCards').html(data);
                    },
                    error: function (data) {
                        alert(data.message)
                    },
                    dataType: "html"
                });

                return false;
            });
        });

        function deleteAdvert(id, btn) {
            if (!confirm("Czy na pewno chcesz usnunąć te ogłoszenie?"))
                return;

            $.ajax({
                type: "POST",
                url: "@Url.Action("RemoveAdvert", "Advert")",
                data: {
                    advertId: id
                },
                dataType: "json"
            })
            .done(function (data) {
                if (data.success) {
                    var elem = btn.parentNode.parentNode.parentNode;
                    elem.parentNode.removeChild(elem);
                } else {
                    alert(data.message)
                }
            })
            .fail(function (data) {
                alert(data.message)
            })

        }

    </script>
}

Adverts/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Adverts/Views/Shared/Components/AdvertCards/Default.cshtml
@model Adverts.Core.ViewModels.AdvertsViewModel


@foreach (var advert in Model.Adverts)
{
    <div class="col">
        <div class="card h-100">
            <img src="@(string.IsNullOrEmpty(advert.MainImageUrl) ? @"\adverts\images\noimage.png" : advert.MainImageUrl)" class="card-img-top" />
            <div class="card-body">
                <h5 class="card-title">@advert.Title</h5>
                <p class="card-text">@advert.Description</p>
            </div>
            <div class="card-footer">
                <a asp-action="GetAdvert" asp-controller="Advert" asp-route-advertId="@advert.Id" class="btn btn-sm btn-outline-secondary">Szczegóły</a>
                @if (Model.UserId == advert.UserId && !string.IsNullOrWhiteSpace(advert.UserId))
                {
                    <button class="btn btn-sm btn-outline-danger" onclick="deleteAdvert('@advert.Id', this)">Usuń</button>
                }
            </div>
        </div>
    </div>
}

Adverts/Views/Shared/_AdvertCards.cshtml
@model Adverts.Core.ViewModels.AdvertsViewModel


@if (!Model.Adverts.Any())
{
    <p class="display-6 text-end">Brak ogłoszeń</p>
}


@foreach (var advert in Model.Adverts)
{
    <div class="col">
        <div class="card h-100">
            <img src="@(string.IsNullOrEmpty(advert.MainImageUrl) ? @"\adverts\images\noimage.png" : advert.MainImageUrl)" class="card-img-top" />
            <div class="card-body">
                <h5 class="card-title">@advert.Title</h5>
                <p class="card-text">@advert.Description</p>
            </div>
            <div class="card-footer">
                <a asp-action="GetAdvert" asp-controller="Advert" asp-route-advertId="@advert.Id" class="btn btn-sm btn-outline-secondary">Szczegóły</a>
                @if (Model.UserId == advert.UserId && !string.IsNullOrWhiteSpace(advert.UserId))
                {
                    <button class="btn btn-sm btn-outline-danger" onclick="deleteAdvert('@advert.Id', this)">Usuń</button>
                }
            </div>
        </div>
    </div>
}

Adverts/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Ogłoszenia</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="col-m navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Advert" asp-action="GetAllAdverts">Ogłoszenia</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Advert" asp-action="AddAdvert">Dodaj nowe ogłoszenie</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Ogłoszenia - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/script.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>